import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { TranslationProvider } from "./context/TranslationContext";
import { TranslateButton } from "./components/TranslateButton";
import { ButtonSizeProvider } from "./context/ButtonSizeContext";
import { ButtonSizeToggle } from "./components/ButtonSizeToggle";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const themeInitScript = `
  (() => {
    const key = "color-mode";
    const root = document.documentElement;
    if (localStorage.getItem(key) === "dark") {
      root.classList.add("dark-mode");
    }
  })();
`;

const themeToggleScript = `
  (() => {
    const key = "color-mode";
    const root = document.documentElement;
    const button = document.getElementById("theme-toggle");
    button?.addEventListener("click", () => {
      const isDark = root.classList.toggle("dark-mode");
      localStorage.setItem(key, isDark ? "dark" : "light");
      button.setAttribute("aria-pressed", String(isDark));
    });
  })();
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {themeInitScript}
        </Script>
      </head>
      <body className="min-h-full flex flex-col">
        <ButtonSizeProvider>
          <TranslationProvider>
            <header className="flex justify-end items-center gap-4 p-4 bg-gray-50 border-b border-gray-200">
              <button
                id="theme-toggle"
                type="button"
                aria-label="Toggle color mode"
                aria-pressed="false"
                className="px-3 py-2 text-sm bg-gray-200 hover:bg-gray-300 rounded-lg transition-colors"
              >
                Dark Mode
              </button>
              <ButtonSizeToggle />
              <TranslateButton />
            </header>
            {children}
          </TranslationProvider>
        </ButtonSizeProvider>
        <Script id="theme-toggle-script" strategy="afterInteractive">
          {themeToggleScript}
        </Script>
      </body>
    </html>
  );
}
