import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { TranslationProvider } from "./context/TranslationContext";
import { ButtonSizeProvider } from "./context/ButtonSizeContext";
import { AccessibilityBar } from "./components/AccessibilityBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const themeInitScript = `
  (() => {
    const key = "color-mode";
    const root = document.documentElement;
    if (localStorage.getItem(key) === "dark") {
      root.classList.add("dark-mode");
    }
  })();
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {themeInitScript}
        </Script>
      </head>
      <body className="h-screen flex flex-col overflow-hidden" suppressHydrationWarning>
        <ButtonSizeProvider>
          <TranslationProvider>
            <AccessibilityBar />
            <div className="flex-1 min-h-0 overflow-auto">
              {children}
            </div>
          </TranslationProvider>
        </ButtonSizeProvider>
      </body>
    </html>
  );
}
